name: Build external CMake library & publish as a branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'compiler'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: macos-14
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v5
        with:
          repository: 'ClassicOldSong/moonlight-common-c'
          submodules: 'true'
          path: 'source'

      - name: Checkout current repository, output branch
        uses: actions/checkout@v5
        with:
          ref: 'main'
          path: 'output'

      - name: Clean output folder
        working-directory: output/
        run: |
          git rm -rf .
          mkdir bin
          mkdir include

      - name: Copy headers
        run: |
          find source/src/ -name '*.h' -exec cp -prv '{}' 'output/include/' ';'

      - name: Prepare and build project - macOS ARM64
        working-directory: source/
        run: |
          cmake -B build-macos-arm64 \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF
          cmake --build build-macos-arm64 --config Release
          cp build-macos-arm64/libmoonlight-common-c.a ../output/bin/libmoonlightcommon.macos-arm64.a

      - name: Commit & push changes
        working-directory: output/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git commit -m "Update static library"; then
            echo "Changes committed."
          else
            echo "No changes to commit."
            exit 0
          fi

          git push
